# =============================================================
# pelicanconf.py — settings used when building the site locally
# (for previewing). Publishing settings live in publishconf.py.
# =============================================================

AUTHOR = 'Alfonso Prado-Cabrero'
SITENAME = 'Alfonso Prado-Cabrero'
SITEDESCRIPTION = 'Personal website of Alfonso Prado-Cabrero'

# Empty for local previewing; publishconf.py sets the real domain.
SITEURL = ''

PATH = 'content'
TIMEZONE = 'Europe/Dublin'
DEFAULT_LANG = 'en'

THEME = 'theme'

# --- URL structure -------------------------------------------
# CRITICAL for SEO: these settings reproduce your existing
# WordPress URLs exactly. An article whose slug is
# "which-omega-3s-are-essential" is published at
#   prado-cabrero.com/which-omega-3s-are-essential/
# which is byte-for-byte what WordPress serves today.
# Do not change these unless you intend URLs to move.
ARTICLE_URL = '{slug}/'
ARTICLE_SAVE_AS = '{slug}/index.html'
PAGE_URL = '{slug}/'
PAGE_SAVE_AS = '{slug}/index.html'

# Turn off Pelican's default category/tag/author archive pages.
# Set any of these to a path if you later want them.
CATEGORY_SAVE_AS = ''
CATEGORIES_SAVE_AS = ''
TAG_SAVE_AS = ''
TAGS_SAVE_AS = ''
AUTHOR_SAVE_AS = ''
AUTHORS_SAVE_AS = ''
ARCHIVES_SAVE_AS = ''

# --- Content locations ---------------------------------------
ARTICLE_PATHS = ['articles']
PAGE_PATHS = ['pages']

# Files copied straight through to the output, unprocessed.
# 'extra' holds CNAME and robots.txt; 'images' holds your
# photos and animated GIFs.
STATIC_PATHS = ['images', 'extra']

# Send the CNAME file to the site root (GitHub Pages needs it
# there for your custom domain) rather than into extra/.
EXTRA_PATH_METADATA = {
    'extra/CNAME': {'path': 'CNAME'},
    'extra/robots.txt': {'path': 'robots.txt'},
}

# --- Home page -----------------------------------------------
DEFAULT_PAGINATION = False
# Newest first
DEFAULT_ORPHANS = 0


# --- Sitemap -------------------------------------------------
# Generated by theme/templates/sitemap.html — no plugin required.
# Submit https://prado-cabrero.com/sitemap.xml to Google Search
# Console once after going live.
DIRECT_TEMPLATES = ['index', 'sitemap']
SITEMAP_SAVE_AS = 'sitemap.xml'

# --- Feeds ---------------------------------------------------
# Disabled locally so builds are fast; publishconf.py turns
# the real RSS feed on.
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# --- Navigation ----------------------------------------------
# Edit these two lists and the nav updates on EVERY page.
MENUITEMS = (
    ('Home', '/'),
    ('Projects', '/projects/'),
    ('Publications', '/publications/'),
    ('About', '/about/'),
    ('Hobbies', '/hobbies/'),
)

FOOTER_LINKS = (
    ('Projects', '/projects/'),
    ('Blog', '/'),
    ('Publications', '/publications/'),
    ('About', '/about/'),
    ('Hobbies', '/hobbies/'),
)

# Format: (name, url, icon filename in content/images/)
SOCIAL = (
    ('ORCID', 'https://orcid.org/0000-0001-8268-5362', 'orcid.webp'),
    ('LinkedIn', 'https://ie.linkedin.com/in/alfonso-prado-cabrero-ab866151/en', 'linkedin.webp'),
    ('ResearchGate', 'https://www.researchgate.net/profile/Alfonso-Prado-Cabrero', 'researchgate.webp'),
)

# --- Author card (appears at the foot of every article) -------
AUTHOR_BIO = ('Senior research fellow at Nutrition Research Centre Ireland, '
              'South East Technological University. Specialised in '
              'biotechnology, genetics and carotenoids.')
AUTHOR_LINK = 'https://ie.linkedin.com/in/alfonso-prado-cabrero-ab866151/en'

# --- Licence -------------------------------------------------
LICENSE_NAME = "Creative Commons Attribution-NonCommercial 4.0 International"
LICENSE_URL = "https://creativecommons.org/licenses/by-nc/4.0/"

# --- Markdown ------------------------------------------------
MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.extra': {},
        'markdown.extensions.meta': {},
        'markdown.extensions.smarty': {},   # proper quotes and dashes
        'markdown.extensions.attr_list': {},  # lets you tag elements, e.g. {: .references }
    },
    'output_format': 'html5',
}

# Don't cache during development, so edits always show up
LOAD_CONTENT_CACHE = False
DELETE_OUTPUT_DIRECTORY = True

# Useful while writing: warn about broken internal links
RELATIVE_URLS = True
